---
image: golang:1.9

cache:
  untracked: true
  paths:
    - vendor

before_script:
    - mkdir -p ${GOPATH}/src/github.com/${CI_PROJECT_PATH}
    - cp -r ${CI_PROJECT_DIR} ${GOPATH}/src/github.com/${CI_PROJECT_NAMESPACE}
    - cd ${GOPATH}/src/github.com/${CI_PROJECT_PATH}
    - go get github.com/Masterminds/glide
    - go get github.com/goreleaser/goreleaser
    - go get -u github.com/golang/lint/golint

stages:
    - build
    - test


test:
    stage: test
    tags:
        - docker
    script:
        - go vet ./...
        - go list ./... | grep -v /vendor/ | xargs -L1 golint
        - go test ./...

compile:
    stage: build
    tags:
        - docker
    script:
        # Add here all the dependencies, or use glide/govendor/...
        # to get them automatically.
        - glide i
        # Better put this in a Makefile
        - go build -race -ldflags "-extldflags '-static'" -o comply
